name: Test

on:
  push:
    paths:
      - 'scripts/**'
      - 'test/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'scripts/**'
      - 'test/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: node --test
